---
# tasks file for jenkins
# Jenkins Install Example

# Make Directory for JAVA
- name: make Directory
  file:
    path: /usr/local/java
    state: directory

# Download OpenJDK,  wget -O /usr/local/java/OpenJDK8.tar.gz https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz
- name: Download OpenJDK
  get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz
    dest: /usr/local/java/OpenJDK8.tar.gz


# Make Unarchive Directory
- name: Make Unarchive Directory
  file:
    path: /usr/local/java/OpenJDK8
    state: directory


# Unarchive a file
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /usr/local/java/OpenJDK8.tar.gz
    dest: /usr/local/java/OpenJDK8
    remote_src: no


# Simbolic Link
- name: Create a symbolic link
  file:
    src: /usr/local/java/OpenJDK8/
    dest: /usr/local/java/jdk
    owner: root
    group: root
    state: link


# Shell
- name: Config JAVA Environment Variable
  sudo: yes
  shell: "{{ item }}"
  with_items:
    - echo "export JAVA_HOME=/usr/local/java/jdk" >>  /etc/profile
    - echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile
    - soucre /etc/profile 



# Import GPG Key(RPM Package Install)

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key


# add and unable jenkins repository 

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: no
    gpgcheck: yes


# Jenkins Install
- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present


# Install font

- name: Install httpd
  yum:
    name: ['dejavu-sans-fonts', 'xorg-x11-server-Xvfb']
    state: installed


# Shell
- name: Config JAVA Environment Variable
  sudo: yes
  shell: 
    sed -i 's/candidates=\"/candidates=\"\n\/usr\/local\/java\/jdk\/bin\/java/g' /etc/init.d/jenkins



# chkconfig enable
- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
 

