---
# tasks file for jenkins
# Jenkins Install Example

# Make Directory for JAVA
- name: make Directory
  file:
    path: /usr/local/java
    state: directory


# Java Install
- name: Install OpenJDK
  shell:
    wget -O /usr/local/java/OpenJDK8.tar.gz https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz
    tar xvfz /usr/local/java/OpenJDK8.tar.gz -C /usr/local/java/OpenJDK8
    ln -s /usr/local/java/OpenJDK8/ jdk


# Import GPG Key(RPM Package Install)

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key


# add and unable jenkins repository 

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: no
    gpgcheck: yes


# Jenkins Install
- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present


# Install font

- name: Install httpd
  yum:
    name: ['dejavu-sans-fonts', 'xorg-x11-server-Xvfb']
    state: installed


# chkconfig enable
- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
 

