- hosts: "{{ test | default( 'localhost' )}}"
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  roles: 
    - codedeploy
  inventory_file: inventory/nodeserver_hosts
  library: library
